import weaviate

def create_chatbot_schema(client, class_name="ChatbotData"):
    """
    Creates a schema class for chatbot-related data. Adjust properties to fit your use case.
    """
    schema = {
        "class": class_name,
        "description": "Stores chatbot conversation data, user inputs, system responses, and metadata",
        "vectorizer": "text2vec-openai",  # Use a vectorizer like 'text2vec-openai'
        "moduleConfig": {
            "text2vec-openai": {"model": "text-embedding-3-small"}  # or "text-embedding-ada-002"
        },
        "properties": [
            {
                "name": "conversation_id",
                "dataType": ["text"],
                "description": "A unique ID for each conversation or session"
            },
            {
                "name": "user_message",
                "dataType": ["text"],
                "description": "The raw text the user inputs"
            },
            {
                "name": "bot_response",
                "dataType": ["text"],
                "description": "The response generated by the chatbot"
            },
            {
                "name": "timestamp",
                "dataType": ["date"],
                "description": "Time when the message was created"
            },
            {
                "name": "intent",
                "dataType": ["text"],
                "description": "Identified user intent (e.g. 'RequestInformation', 'SmallTalk', etc.)"
            },
            {
                "name": "emotion",
                "dataType": ["text"],
                "description": "Detected user emotion (e.g. 'happy', 'sad', or 'frustrated')"
            },
            {
                "name": "confidence_score",
                "dataType": ["number"],
                "description": "A numeric confidence score for the intent/emotion detection"
            },
            {
                "name": "metadata",
                "dataType": ["text[]"],
                "description": "Miscellaneous metadata or tags related to the conversation"
            }
        ]
    }

    # Create the schema in Weaviate
    client.schema.create_class(schema)
    print(f"Chatbot schema '{class_name}' created successfully!")